spring:
  application:
    name: flow-sync
  security:
    user:
      name: user
      password: user
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/flow-sync
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
